CREATE TABLE `clientes` (
	`id` INT(10) NULL DEFAULT NULL,
	`fechaalta` DATE NULL DEFAULT NULL,
	`fechabaja` DATE NULL DEFAULT NULL,
	`estado` VARCHAR(1) NULL DEFAULT NULL COMMENT '(A)ctivo, (B)aja' COLLATE 'utf8_spanish_ci',
	`tipodocumento` VARCHAR(1) NULL DEFAULT NULL COMMENT '(1)NIF, (2)CIF, (3)NIE, (4)Pasaporte, (5)Otro' COLLATE 'utf8_spanish_ci',
	`identidicador` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`fechadevalidez` DATE NULL DEFAULT NULL,
	`nombre` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`apellido1` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`apellido2` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`alias` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`direccion` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`codigopostal` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`poblacion` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`provincia` INT(11) NULL DEFAULT NULL,
	`telefono1` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`telefono2` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`fax` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`mastelefonos` BLOB NULL,
	`fechanacimiento` DATE NULL DEFAULT NULL,
	`onomastica` DATE NULL DEFAULT NULL,
	`fechacarneta` DATE NULL DEFAULT NULL,
	`validezcarneta` DATE NULL DEFAULT NULL,
	`fechacarneta1` DATE NULL DEFAULT NULL,
	`validezcarneta1` DATE NULL DEFAULT NULL,
	`fechacarneta2` DATE NULL DEFAULT NULL,
	`validezcarneta2` DATE NULL DEFAULT NULL,
	`fechacarnetb` DATE NULL DEFAULT NULL,
	`validezcarnetb` DATE NULL DEFAULT NULL,
	`fechacarnetc` DATE NULL DEFAULT NULL,
	`validezcarnetc` DATE NULL DEFAULT NULL,
	`fechacarnetd` DATE NULL DEFAULT NULL,
	`validezcarnetd` DATE NULL DEFAULT NULL,
	`cuentabancaria` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`email` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`web` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`formacontacto` VARCHAR(1) NULL DEFAULT NULL COMMENT '(1)Email, (2)Carta, (3)SMS' COLLATE 'utf8_spanish_ci',
	`profesion` INT(11) NULL DEFAULT NULL,
	`detalle` BLOB NULL,
	`observaciones` BLOB NULL,
	`incidencias` BLOB NULL,
	`comercial` BLOB NULL,
	`enviarpublicidad` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`impresolopd` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`firmadolopd` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`sexo` VARCHAR(1) NULL DEFAULT NULL COMMENT '(H)ombre, (M)ujer' COLLATE 'utf8_spanish_ci',
	`estadocivil` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`hijos` INT(11) NULL DEFAULT NULL,
	`situacionlaboral` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`rentaanual` DECIMAL(12,2) NULL DEFAULT NULL,
	`capacidadahorro` DECIMAL(12,2) NULL DEFAULT NULL,
	`colaborador` INT(11) NULL DEFAULT NULL,
	`fechacreacion` DATETIME NULL DEFAULT NULL,
	`usuariocreacion` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci',
	`fechaultimamodificacion` DATETIME NULL DEFAULT NULL,
	`usuarioultimamodificacion` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_spanish_ci'
)
COLLATE='utf8_spanish_ci'
ENGINE=InnoDB;

